In [1]:
import numpy as np

#### File Header block

In [53]:
# Properties

version = 1
n_data_blocks = 0
start_data = 86 # This depends on the Coordinate system Block
size_data_blocks = 0
offsets = [0,0,0]
mesh_size = 0

In [27]:
# Magic
p1 = np.array('REX1', dtype='bytes')
p1, p1.nbytes

(array(b'REX1', dtype='|S4'), 4)

In [30]:
# version
p2 = np.array(version, dtype='uint16')
p2, p2.nbytes

(array(1, dtype=uint16), 2)

In [32]:
#  CRC32
p3 = np.array(0, dtype='uint32')
p3, p3.nbytes

(array(0, dtype=uint32), 4)

In [37]:
# n_data_blocks 
p4 = np.array(n_data_blocks, dtype='uint16')
p4, p4.nbytes

(array(0, dtype=uint16), 2)

In [38]:
# start_data
p5 = np.array(start_data, dtype='uint16')
p5, p5.nbytes

(array(86, dtype=uint16), 2)

In [ ]:
# Size data Blcks

In [74]:
# reserved

res = np.array([0]*42, dtype='bytes')
res, res.tobytes(), res.nbytes

(array([b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0',
        b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0',
        b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0',
        b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0', b'0'], dtype='|S1'),
 b'000000000000000000000000000000000000000000',
 42)

In [81]:
a + p4.tobytes() + res.tobytes()

bytearray(b'\x00\x00000000000000000000000000000000000000000000')

In [80]:
a = bytearray()

#### Coordinate system block

In [39]:
# srid
p6 = np.array(3876, dtype='uint32')
p6, p6.nbytes

(array(3876, dtype=uint32), 4)

In [42]:
# authname
p7 = np.array('EPSG', dtype='bytes')
p7, p7.nbytes

(array(b'EPSG', dtype='|S4'), 4)

In [46]:
# offsets
p8 = np.array(offsets, dtype='float32')
p8, p8.nbytes

(array([0., 0., 0.], dtype=float32), 12)

#### Data block: Mesh
##### Data header

In [49]:
# Data block type
p9 = np.array(3, dtype='uint16')
p9, p9.nbytes

(array(3, dtype=uint16), 2)

In [52]:
# version

p10 = np.array(1, dtype='uint16')
p10, p10.nbytes

(array(1, dtype=uint16), 2)

In [54]:
# size 
p11 = np.array(mesh_size, dtype='uint32')
p11, p11.nbytes

(array(0, dtype=uint32), 4)

In [59]:
# dataId
p12 = np.array(1, dtype='uint64')
p12, p12.nbytes

(array(1, dtype=uint64), 8)

##### Datatype MEsh

In [62]:
# attributes

# size of arrays
n_vtx_coord = 3
n_nor_coord = 0
n_tex_coord = 0
n_vtx_colors = 0
n_triangles = 0

# Start points
start_vtx_coord = 3
start_nor_coord = 0
start_tex_coord = 0
start_vtx_colors = 0
start_triangles = 0



In [61]:
# level of detail
p13 = np.array([1,1], dtype='uint16')

p13, p13.nbytes

(array([1, 1], dtype=uint16), 4)

In [65]:
# size and start points
p14 = np.array([n_vtx_coord, n_nor_coord, n_tex_coord, n_vtx_colors, n_triangles, start_vtx_coord, 
                start_nor_coord, start_tex_coord, start_vtx_colors, start_triangles], dtype='uint32')
p14, p14.nbytes

(array([3, 0, 0, 0, 0, 3, 0, 0, 0, 0], dtype=uint32), 40)

In [67]:
# materialid

p15 = np.array(0, dtype='uint64')
p15, p15.nbytes

(array(0, dtype=uint64), 8)

In [82]:
' ' * 74

'                                                                          '

In [69]:
# string size and string
p17 = np.array('foo', dtype='bytes') # This has to be always 74 bytes
p16 = np.array(p17.nbytes, dtype='uint16')

p16, p16.nbytes, p17, p17.nbytes

(array(3, dtype=uint16), 2, array(b'foo', dtype='|S3'), 3)

#### Vertex coordinates block

In [ ]:
meshHeaderSize   = 128

In [89]:
a = np.array([]).tobytes()

In [88]:

np.appennp.array([2,4,6])

array([2, 4, 6])

In [91]:

b = bytearray(a)

In [92]:
newFile = open("test.rex", "wb")
# write to file
newFile.write(b)

0